### ISSUE TITLE
Hello World Build Fails

### ISSUE THREAD

**Issue by MavenAR** [everysight-maverick/sdk#7]
Trying  to build Hello World with XCode set to version 14, receive this error:

Failed to build module 'EvsKit'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.8.1 (swiftlang-5.8.0.124.5 clang-1403.0.22.11.100)', while this compiler is 'Apple Swift version 5.9 (swiftlang-5.9.0.128.108 clang-1500.0.40.1)'). Please select a toolchain which matches the SDK.

Tried to roll back Swift to version 4 but same error.

**Comment by feranf** [comment]
Hi @MavenAR, 
Did you manage to build the example or do you need support?

**Comment by MavenAR** [comment]
Thank for the reply… I got it going and was able to successfully complete Hello World.

Keith
